name: PR Build Check

on:
  pull_request: 
jobs:
  java:
    name: Build and Test Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: gradle build
  isthmus-native-image-mac-linux:
    name: Build Isthmus Native Image
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive      
    - uses: DeLaGuardo/setup-graalvm@5.0
      with:
        graalvm: '22.0.0.2'
        java: 'java17'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Report Java Version
      run: java -version
    - name: Install GraalVM native image
      run: gu install native-image
    - name: Build with Gradle
      run: gradle nativeImage
    - name: Smoke Test
      run: ./isthmus/src/test/script/smoke.sh
    - name: Rename the artifact to OS-unique name
      shell: bash
      run: |
        value=`mv isthmus/build/graal/isthmus isthmus/build/graal/isthmus-${{ matrix.os }}`
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: isthmus-${{ matrix.os }}
        path: isthmus/build/graal/isthmus-${{ matrix.os }}
