name: PR Build Check

on:
  pull_request:
jobs:
  editorconfig-checker:
    name: Check editorconfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
  commitlint:
    name: Lint commits for semantic-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npx commitlint --from=${{ github.event.pull_request.base.sha }} --to=${{ github.sha }} --verbose
  security:
    name: Security validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
  java:
    name: Build and Test Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: gradle build
  isthmus-native-image-mac-linux:
    name: Build Isthmus Native Image
    needs: java
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '17'
        distribution: 'graalvm'
        # helps avoid rate-limiting issues
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Report Java Version
      run: java -version
    - name: Install GraalVM native image
      run: gu install native-image
    - name: Build with Gradle
      run: gradle nativeImage
    - name: Smoke Test
      run: ./isthmus/src/test/script/smoke.sh
        ./isthmus/src/test/script/tpch_smoke.sh
    - name: Rename the artifact to OS-unique name
      shell: bash
      run: |
        value=`mv isthmus/build/graal/isthmus isthmus/build/graal/isthmus-${{ matrix.os }}`
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: isthmus-${{ matrix.os }}
        path: isthmus/build/graal/isthmus-${{ matrix.os }}
  dry-run-release:
    name: Dry-run release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Check current status before next release
        run: ./ci/release/dry_run.sh
